spring:
  jmx:
    enabled : true
  application:
    name: email-app-api
  web:
    resources:
      add-mappings: false 
  mail:
   username: blessedbins007@gmail.com
   password: ayyjiomcxgbabzrk
   host: smtp.gmail.com
   port: 587
   protocol: smtp
   default-encoding: UTF-8
   properties:
     mail:
       smtp:
         auth: true
         starttls:
            enable: true
   
email:
   from: blessedbins007@gmail.com
   cc: bindishaparmar01@gmail.com
   bcc: bindishaparmar01@gmail.com
   
jasypt:
  encryptor:
    algorithm: PBEWITHSHA256AND256BITAES-CBC-BC
    provider-class-name: org.bouncycastle.jce.provider.BouncyCastleProvider
