spring:
  jmx:
    enabled : true
  application:
    name: email-app-api
  web:
    resources:
      add-mappings: false 
  mail:
   username: ENC(J7vz3WlRp0at9Iow3eMmnGyJfNKHRPlMOFpdpzHwMjYGl57ItG/VnpeHxEdLLTVK/BpShsC62kIMPYLB6YTxDclGwtJzdFCUVNMAoQMPRkE=)
   password: ENC(6xUczKwOrRVXjJviE8vIDxs1ymI8RpSmrdSo+u2VFsLWwZldjC8jhubeDa+qpMuwRMOfRMI1pKyRusW1w5+cVg==)
   host: smtp.gmail.com
   port: 587
   protocol: smtp
   default-encoding: UTF-8
   properties:
     mail:
       smtp:
         auth: true
         starttls:
            enable: true
   
email:
   from: developersjourneysource@gmail.com
   cc: bindishaparmar01@gmail.com
   bcc: bindishaparmar01@gmail.com
   
jasypt:
  encryptor:
    algorithm: PBEWITHSHA256AND256BITAES-CBC-BC
    provider-class-name: org.bouncycastle.jce.provider.BouncyCastleProvider
    password: IamBatman@07   